spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notioniq?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Root@#&1999
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: notionIQ

server:
  port: 8081